hashicorp/vault-csi-provider

- Makefile
- main.go
- version.go
- version_test.go
fixes https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/issues/18
```
root@k8s-agentpool1-32372105-vmss000000:/etc/kubernetes/secrets-store-csi-providers/vault# ./provider-vault --version
{"version":"addversion02","buildDate":"2019-12-11-20:35","minDriverVersion":"v0.0.8"}
```
> add --version flag

- README.md
- examples/nginx-pod-vault-inline-volume-secretproviderclass.yaml
- examples/nginx-pod-vault-inline-volume.yaml
- examples/pv-vault-csi.yaml
- Driver version `v0.0.8` has been released with the driver name changes. Updating all the examples and tests to reflect the new driver name.
> update driver name in examples and tests

- Makefile
This dependency is not installed through a setup or go get in the
README.
I found that the previous URLs were not correct.
> Fixes make test

- Makefile
This task has no effort and violates the Hashicorp Eng principles for naming.
https://github.com/hashicorp/engineering-docs/blob/master/writing/style-guide.md#ableism
> Removes unused task with poor name

- provider.go
- provider_test.go
I've tried to keep this fairly targeted, but also resilient to surprising paths or deployments, including Windows nodes, while also making it easy and reliable to test on any OS. Unfortunately the existing test coverage is pretty low, so it's a big task to write more of an integrated test.
> Enforce descending directory write path

- Makefile
This ensures builds run on a Mac still produce a binary that honours the file name and also a working linux-based Docker container.
> Set GOOS and GOARCH for build target

- Makefile
- internal/version/version.go
- internal/version/version_test.go
- main.go
Following up on a comment from #61.
```bash
./_output/secrets-store-csi-driver-provider-vault_darwin_amd64_0.0.7 --version
{"version":"0.0.7","buildDate":"2021-02-04-15:38","goVersion":"go version go1.15.7 darwin/amd64","minDriverVersion":"v0.0.17"}
```
> Add go build version to version info

- Dockerfile
- Makefile
- test/bats/configs/nginx-dynamic-creds.yaml
- test/bats/configs/nginx-env-var.yaml
- test/bats/configs/nginx-inline-volume.yaml
- test/bats/configs/nginx-multiple-volumes.yaml
- test/bats/configs/nginx-pki.yaml
- test/bats/configs/postgres-client.yaml
- test/bats/configs/postgres.yaml
This removes all references to `hashicorp.jfrog.io` which has been replaced with a self-hosted registry, `docker.mirror.hashicorp.services`
> Remove jfrog references

- test/bats/configs/nginx/Chart.yaml
- test/bats/configs/vault/Chart.yaml
It looks like helm 3.5.3 is more strict about [chart versions and semver](https://helm.sh/docs/topics/charts/#charts-and-versioning). I was getting this error when setting up e2e tests locally:
```
helm install vault-bootstrap test/bats/configs/vault \
--namespace=csi
Error: validation: chart.metadata.version "test" is invalid
make: *** [e2e-setup] Error 1
```
This PR just adds a 0 to satisfy semver 2.
> Add semver 2 versions to test charts

- deployment/provider-vault-installer.yaml
- main.go
In order to support readiness and liveness probes, we need a health handler. This creates a simple HTTP handler that return a 204 if it's receiving traffic.
The current e2e tests will automatically test this feature because I added the probes to the deployment and the setup code uses the `kubectl --wait` functionality. If the probes aren't working the pods will never go ready.
> Add health handler

- Makefile
These changes were useful when cleaning up a partial setup locally, otherwise the csi namespace wasn't being deleted (and subsequent test setups would then fail).
> Make the e2e-teardown a little more robust

- .circleci/config.yml
- CHANGELOG.md
- Dockerfile
- Makefile
- README.md
- deployment/provider-vault-installer.yaml
- go.mod
- internal/client/client.go
- internal/client/client_test.go
- internal/provider/provider.go
- internal/provider/provider_test.go
- internal/server/server.go
- main.go
- sample/ingress-controller-tls/README.md
- test/bats/configs/vault-csi-provider.yaml
- test/bats/provider.bats
In anticipation of simplifying the repository names (project and docker), I've made the necessary changes to the project files. The new name of this project is `vault-csi-provider`.
The published docker repository will be left unchanged to support older releases of CSI, however, a new repository will be created and all images will be published there moving forward.
I've left the repository in the deployment file alone as this currently points to the latest experimental release. We'll want to update this when we release the new provider.
> Simplify repository name

- Makefile
- manifest_staging/deployment/provider-vault-installer.yaml
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
- Adds manifest_staging dir to host yaml updates prior to release.
Fixes https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/issues/74
> chore: use manifest_staging dir for yaml changes

- CHANGELOG.md
There are no changes to the minimum required version of Kubernetes, this was meant to be placeholder text until that was confirmed.
> Remove changelog placeholder

- manifest_staging/deployment/provider-vault-installer.yaml
Consistently use `vault-csi-provider` over other variants.
> Small consistency tweaks for staging manifest

- README.md
Now that we have released 0.1.0, updating the experimental label to reflect increased stability with which we will attempt to maintain this product. It's important to be upfront about the fact that we are relying on alpha features, but we will endeavour to provide upgrade paths and deprecation notices going forwards.
> Update experimental notice to beta

- CHANGELOG.md
- Makefile
- internal/config/config_test.go
- internal/provider/provider.go
- main.go
#89 spotted un unhandled error. The error path should be pretty unlikely which is why I guess this was uncaught until now, but it's a pretty ugly bug nonetheless, so I've added some extra linters to our CI.
The `ineffassign` linter catches this prior to fixing (as well as one additional case), and I also added `errcheck` (which caught an additional two), and `unused` is unrelated but I added it as it seems like a nice and uncontroversial check to have.
> Fix unhandled errors

- .circleci/config.yml
- CHANGELOG.md
- Makefile
- main.go
- main_test.go
This PR makes our flags consistent on using dashes instead of underscores as with our other products. To help support that in a forwards-compatible way, I've left `--health_addr` in there for now (because it's the only underscore argument we've released) but marked it as deprecated, and if someone specifies both `--health_addr` and `--health-addr`, the one that occurs later in the command line wins.
This PR also adds a couple of `make` targets and updated CI config to support running tests with both behaviours of `--write-secrets`. It's a pretty significant change in the operation of the provider because it controls whether the provider or the driver writes the secrets, so I'd like to keep good test coverage of both flows until `--write-secrets=true` becomes a deprecated behaviour a few …
> Consistent flags and CI for --write-secrets=false

- CHANGELOG.md
- deployment/vault-csi-provider.yaml
- manifest_staging/deployment/vault-csi-provider.yaml
Getting ready to release 0.3.0
* Support for changing the default Vault address and Kubernetes mount path via CLI flag to the vault-csi-provider binary [[GH-96](https://github.com/hashicorp/vault-csi-provider/pull/96)]
* Support for sending secret contents to driver for writing via `--write-secrets=false` [[GH-89](https://github.com/hashicorp/vault-csi-provider/pull/89)]
* **Note:** `--write-secrets=false` will become the default from v0.4.0 and require secrets-store-csi-driver v0.0.21+
* `--health_addr` flag is marked deprecated and replaced by `--health-addr`. Slated for removal in v0.5.0 [[GH-100](https://github.com/hashicorp/vault-csi-provider/pull/100)]
* Added missing error handling when transforming SecretProviderClass config to a Vault request …
> Update versions and changelog for 0.3.0

- README.md
The driver is now v1, although not all features are stable. See https://secrets-store-csi-driver.sigs.k8s.io/ for details of project status.
The features still currently in alpha are:
* Auto rotation
* Sync with Kubernetes secrets
> Remove beta notice

- CHANGELOG.md
- Makefile
- internal/version/version.go
- main.go
- manifest_staging/deployment/vault-csi-provider.yaml
As per the upstream driver project, sending secret contents upstream for the driver to write to file needs to become the default. This gets rid of one of the `hostPath` volumes required in the default manifest, as the provider no longer needs to directly write to pods' mounts with this default.
> Flip default value for -write-secrets flag

- CHANGELOG.md
- internal/provider/provider.go
- internal/provider/provider_test.go
Resolves #115 and based on code from #122. You can put arbitrary JSON data into `kv`'s values (and theoretically other secret engines could do the same) using a JSON file and a command like `vault kv put secret/test @test.json`, and this PR allows `vault-csi-provider` to specifically select that JSON data without having to escape your secret JSON into a big ugly string when storing it in Vault.
This PR does _not_ address arbitrary paths within the JSON though. Vault's API itself enforces that the top-level data object is a map, and users should be able to select any single top-level key from that object.
Strings remain special-cased so that we continue to write string values without wrapping them in quotes.
> Support JSON values for secretKey

- .circleci/config.yml
- .github/workflows/build.yml
- .gitignore
- .release/ci.hcl
- .release/security-scan.hcl
- Dockerfile
- Makefile
Updates to use CRT for releases:
* New GitHub action to create the artefacts for promotion
* New CRT config files
* Dockerfile restructured for dev/CI targets
* Various Makefile updates
> Use CRT for releases

- CHANGELOG.md
- deployment/vault-csi-provider.yaml
- manifest_staging/deployment/vault-csi-provider.yaml
Getting the repo ready to trigger the release process. This could have easily been 1.0.0, but the plan is to save that for the second run of the new release process, and most likely try to keep changes to a minimum too.
> Prepare to release 0.4.0

- .circleci/config.yml
- .github/workflows/build.yml
- .release/ci.hcl
- CHANGELOG.md
- Makefile
- internal/provider/provider.go
- internal/server/server.go
- main.go
Preparing for v1.0.0 by removing deprecated flags. These have previously been marked deprecated in the changelog and release notes.
> Deprecate -write-secrets and -health_addr flags

- CHANGELOG.md
- internal/config/config.go
- internal/config/config_test.go
- internal/config/testdata/example-parameters-string.txt
- internal/provider/provider.go
- test/bats/configs/vault-kv-custom-audience-secretproviderclass.yaml
- test/bats/configs/vault-policy-kv-custom-audience.hcl
- test/bats/provider.bats
Allow optionally specifying the audience in the SecretProviderClass to allow a safe usage of the ["audience" parameter in the Vault Kubernetes auth method](https://www.vaultproject.io/api-docs/auth/kubernetes#:~:text=audience%20(string%3A%20%22%22)%20%2D%20Optional%20Audience%20claim%20to%20verify%20in%20the%20JWT.).
If a custom audience is specified, it is required to use as reviewer JWT in Vault something different from [the client JWT](https://www.vaultproject.io/docs/auth/kubernetes#use-the-vault-client-s-jwt-as-the-reviewer-jwt).
This PR was tested against GKE, using a [static token as reviewer JWT](https://www.vaultproject.io/docs/auth/kubernetes#continue-using-long-lived-tokens).
Example usage:
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata: …
```
> feat: allow customizing the "aud" claim in the JWT

- CHANGELOG.md
- go.mod
- internal/config/config.go
- internal/config/config_test.go
- internal/provider/provider.go
- test/bats/configs/vault-kv-secretproviderclass.yaml
- test/bats/provider.bats
Adds a new `filePermission` option in the SecretProviderClass parameters to set the permissions mounted files should be given. This was a feature brought up in the most recent community call, and is particularly helpful for secrets like private keys, where tooling will reject or print warnings when their permissions are too open.
> Support file permission setting in SPC

- CHANGELOG.md
- go.sum
- internal/config/config.go
- internal/config/config_test.go
- internal/provider/provider.go
- internal/provider/provider_test.go
- internal/server/server.go
- main.go
Closes #146 
* Generate a version based on the secret inputs and contents so that downstream consumers can tell the secret has been rotated
* Generate an error when duplicate object names are used so that we can confidently use object name as the key for versions we return - this was essentially a bug we didn't catch before because it results in overwriting files
* Create a higher level unit test with mocked HTTP servers so we can verify the version behaviour nearer the API level.
This PR also deletes some unused code (`writeSecret()` and `validateFilePath()`) along with their tests now that the provider no longer supports writing secrets itself. Happy to split that out into a separate PR if it makes the diff tricky to read.
> Report secret version as a hash of the input and contents

- CHANGELOG.md
- main.go
Goes hand-in-hand with https://github.com/hashicorp/vault-helm/pull/745.
This doesn't actually change the default, as it was already set to the same default as set in the [`api` package](https://github.com/hashicorp/vault/blob/f4f1646fe3f7fbed8b1173630bc6a51d96d09599/api/client.go#L220). It does, however, allow the `VAULT_ADDR` environment variable to have an effect.
> Unset -vault-addr flag default

- go.mod
- go.sum
Update deps to address recent [YAML package CVE](https://github.com/advisories/GHSA-hp87-p4gw-j4gq).
> Update testify and YAML deps

- CHANGELOG.md
- internal/provider/provider.go
- internal/provider/provider_test.go
This PR fixed #165, ensuring we check for the key existence before we pass it into json.Marshal. 
`data[secretKey]` returns `nil` and `json.Marshal(nil)` hides the fact that the secretKey doesn't exist. 
```
➜ make test 
gotestsum --format=short-verbose 
PASS internal/version.TestGetVersion (0.00s)
PASS internal/version
PASS internal/config.TestParseParametersFromYaml (0.00s)
PASS internal/config.TestParseParameters (0.00s)
PASS internal/config.TestParseConfig (0.00s)
PASS internal/config.TestParseConfig_Errors (0.00s)
PASS internal/config.TestValidateConfig (0.00s)
PASS internal/config
PASS TestListen (0.00s)
PASS .
PASS internal/provider.TestEnsureV1Prefix (0.00s)
PASS internal/provider.TestGenerateRequest (0.00s)
PASS internal/provider.TestKeyFromData (0.00s)
PASS …
```
> Ensure we check for the key to exist before attempting to read it

- .github/workflows/jira.yaml
Here's an example of a failed action: https://github.com/hashicorp/vault-csi-provider/runs/7695714775?check_suite_focus=true
> Fix close transition for jira action

- .github/workflows/build.yml
I'm not sure why, but the build action stopped running on #169 once it got closed and re-opened, so I missed that there was a syntax error here. Here's an example of it now working on this PR: https://github.com/hashicorp/vault-csi-provider/runs/7696116659?check_suite_focus=true
> Fix CRT action syntax for appending SHA

- .github/workflows/build.yml
Future releases will be released to the public HashiCorp repositories on both Docker Hub and ECR
Closes #162
> Publish future images to public ECR

- CHANGELOG.md
- go.mod
- go.sum
Updated deps to avoid [GO-2022-0969](https://pkg.go.dev/vuln/GO-2022-0969) and [GO-2022-1059](https://pkg.go.dev/vuln/GO-2022-1059)
```console
❯ go get golang.org/x/text@latest golang.org/x/net@latest
go: upgraded golang.org/x/net v0.0.0-20220722155237-a158d28d115b => v0.0.0-20221012135044-0b7e1fb9d458
go: upgraded golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f => v0.0.0-20220728004956-3c1f35247d10
go: upgraded golang.org/x/text v0.3.7 => v0.3.8
❯ go mod tidy
```
> update system deps

- CHANGELOG.md
- internal/config/config.go
- internal/config/config_test.go
- internal/provider/provider.go
- internal/provider/provider_test.go
- test/bats/configs/vault-kv-sync-secretproviderclass.yaml
- test/bats/provider.bats
Added support for encoded secrets (#106). This makes sense e.g. in the context of non-UTF-8 encoded certificates, like pfx.
This would allow storing e.g. 
* asymmetric private/public key pairs for Pulsar
* certificates for Elasticsearch
as base64 encoded strings in Vault.
Since this is my first go with go (pun intended) I would appreciate any feedback.
> Support Encoding of Secrets

- .github/workflows/build.yml
- .github/workflows/tests.yaml
- Makefile
- test/bats/configs/vault/vault.values.yaml
- test/bats/provider.bats
The integration tests were still using a very old version of Vault Enterprise that allowed users to run it for a limited time without a license. Added a license to the repo so we can test a newer version of Vault, and also added some conditionals so that OSS users can run most of the tests themselves without requiring a license.
> Update integration tests to use latest Vault

- CHANGELOG.md
- Makefile
- internal/auth/kubernetes_jwt.go
- internal/client/client.go
- internal/client/client_test.go
- internal/config/config.go
- internal/config/config_test.go
- internal/provider/provider.go
- internal/provider/provider_test.go
- internal/server/server.go
- main.go
- test/bats/configs/cluster-resources.yaml
- test/bats/configs/vault-kv-secretproviderclass-jwt-auth.yaml
- test/bats/provider.bats
Someone pointed out that JWT auth already works because the login endpoints are identical for [kubernetes](https://developer.hashicorp.com/vault/api-docs/auth/kubernetes#login) and [JWT](https://developer.hashicorp.com/vault/api-docs/auth/jwt#jwt-login). This just improves the naming and adds an integration test for the purpose of regression testing so that we can officially document JWT auth as supported.
> Support JWT auth

- CHANGELOG.md
- README.md
- deployment/vault-csi-provider.yaml
- manifest_staging/deployment/vault-csi-provider.yaml
* SecretProviderClass objects now also accept `spec.parameters.vaultAuthMountPath` as an alternative to `spec.parameters.vaultKubernetesMountPath`. [[GH-210](https://github.com/hashicorp/vault-csi-provider/pull/210)]
* The Provider will cache a Vault token per requesting pod in memory and re-use it until it expires. [[GH-202](https://github.com/hashicorp/vault-csi-provider/pull/202)]
* JWT auth is supported by setting role name and auth mount path in the same way as for Kubernetes auth. [[GH-210](https://github.com/hashicorp/vault-csi-provider/pull/210)]
> Prepare 1.4.0 release

- .github/workflows/build.yml
It looks like updating the run name might be what broke CRT release automation.
> Revert name of build.yml jobs to default

- .github/workflows/tests.yaml
- Add k8s 1.29.2 to the k8s version test matrix. 
- Bump all previous minor versions.
> Test against k8s 1.29

- go.mod
- go.sum
Fixes [security scan failure](https://github.com/hashicorp/crt-workflows-common/actions/runs/8237340656/job/22525992785) due to https://pkg.go.dev/vuln/GO-2024-2611
> Bump google.golang.org/protobuf from 1.30.0 to 1.33.0

- Makefile
- README.md
- test/bats/configs/vault/vault.values.yaml
Also sets the agent image for csi to match vault server in the e2e test setup, and adds the security disclosure blurb to the README.
> Update csi driver and vault-helm versions in tests

- .github/actions/integration-test/action.yml
- .github/workflows/build.yml
- .github/workflows/tests.yaml
Other fixes
- store exported kind logs in GH which will make it easier to debug the CI tests
- test against vault 1.16.2
- update vault license
> Bump GH actions for node 16 obsolescence

- .github/workflows/tests.yaml
- Makefile
Use vault-helm v0.28.1 and Vault 1.17.2 in tests.
> Test with latest chart and vault 1.17 versions

- .github/workflows/tests.yaml
- CHANGELOG.md
- Makefile
Drop 1.26, add 1.31
Bump Vault versions
> Vault 31629/bump k8s version
